### ISSUE TITLE
Question: library still supported?

### ISSUE THREAD

**Issue by zelenij** [thoth-org/Thoth.Elmish.FormBuilder#31]
Looks like a library I could use in my project. I can see there are some recent commits, but the latest Nuget package is from 2019. Any indication on how this aligns?

**Comment by MangelMaxime** [comment]
Hello @zelenij,

your message is kind of coming at the right time. I am saying that because, I am planing to make it enter "maintenance state" because I am designing a new form library which solves all the limitation I have with this one.

With that said, please know that this library is used in production since 2018 without problem and I will keep supporting it for bug fixes after I merged #29.

The major limitation I have with the current design of this library are:
- HMR support is not working as expected so you need to do a full refresh
- If you are making some request to fetch data on your server to get autocomplete or a list of values for a select for example you will need to store the `formConfig` in a `mutable` variable or your application `Model`. Because I didn't thought about passing the session in via the builder interface..

Those limitations are more related to user experience than bugs or anything like that.

For me Thoth.Elmish.FormBuilder, is considered **stable** and cover the scope/needs I wanted it to cover.

From my point of view, you can start using this library and if you are happy with it keep using it or move to my new library when it will be released and if you like it too. They both share a similar philosophy (not polluting your Msg type with one message per input) and so should not be hard to make the transition.

**Comment by zelenij** [comment]
I see, thanks for the detailed answer.

**Comment by MangelMaxime** [comment]
Hello @zelenij,

[Fable.Form](https://mangelmaxime.github.io/Fable.Form/) has been published.
